// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_volt1;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_battery;
lv_obj_t * ui_usb;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_joystick;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_volt3;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_battery2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_signal;
lv_obj_t * ui_rssi;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_Panel6(lv_event_t * e);
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label5;
void ui_event_Panel7(lv_event_t * e);
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label6;
void ui_event_Panel8(lv_event_t * e);
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label7;
void ui_event_Panel9(lv_event_t * e);
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label8;
void ui_event_Panel10(lv_event_t * e);
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label9;
void ui_event_Panel11(lv_event_t * e);
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label10;
void ui_event_Panel12(lv_event_t * e);
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label11;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label13;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label14;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label15;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label16;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label17;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
void ui_event_Panel19(lv_event_t * e);
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Label18;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label19;
void ui_event_Panel21(lv_event_t * e);
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
void ui_event_Panel23(lv_event_t * e);
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Panel24;
void ui_event_Label24(lv_event_t * e);
lv_obj_t * ui_Label24;
void ui_event_Label25(lv_event_t * e);
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label26;
void ui_event_Panel25(lv_event_t * e);
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Panel54;
lv_obj_t * ui_Label61;
void ui_event_Dropdown12(lv_event_t * e);
lv_obj_t * ui_Dropdown12;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_Label30;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_Label31;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
void ui_event_Panel30(lv_event_t * e);
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Label32;


// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t * ui_Screen6;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Label33;
void ui_event_Panel32(lv_event_t * e);
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label34;
void ui_event_Panel33(lv_event_t * e);
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Label35;
void ui_event_Panel34(lv_event_t * e);
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;


// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t * ui_Screen7;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Label40;
void ui_event_Dropdown3(lv_event_t * e);
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Panel38;
lv_obj_t * ui_Label41;
void ui_event_Dropdown4(lv_event_t * e);
lv_obj_t * ui_Dropdown4;
lv_obj_t * ui_Panel39;
lv_obj_t * ui_Label42;
void ui_event_Dropdown5(lv_event_t * e);
lv_obj_t * ui_Dropdown5;
lv_obj_t * ui_Panel40;
lv_obj_t * ui_Label43;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label44;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
void ui_event_Panel41(lv_event_t * e);
lv_obj_t * ui_Panel41;
lv_obj_t * ui_Label45;


// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
lv_obj_t * ui_Screen8;
lv_obj_t * ui_Panel42;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Panel43;
lv_obj_t * ui_Label47;
void ui_event_Dropdown6(lv_event_t * e);
lv_obj_t * ui_Dropdown6;
lv_obj_t * ui_Panel44;
lv_obj_t * ui_Label48;
void ui_event_Dropdown7(lv_event_t * e);
lv_obj_t * ui_Dropdown7;
lv_obj_t * ui_Panel45;
lv_obj_t * ui_Label49;
void ui_event_Dropdown8(lv_event_t * e);
lv_obj_t * ui_Dropdown8;
lv_obj_t * ui_Panel46;
lv_obj_t * ui_Label50;
void ui_event_Dropdown9(lv_event_t * e);
lv_obj_t * ui_Dropdown9;
lv_obj_t * ui_Panel47;
lv_obj_t * ui_Label51;
void ui_event_Dropdown10(lv_event_t * e);
lv_obj_t * ui_Dropdown10;
lv_obj_t * ui_Panel48;
lv_obj_t * ui_Label52;
void ui_event_Dropdown11(lv_event_t * e);
lv_obj_t * ui_Dropdown11;
lv_obj_t * ui_Panel49;
lv_obj_t * ui_Label53;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label54;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Panel50;
lv_obj_t * ui_Label55;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label56;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Panel51;
lv_obj_t * ui_Label57;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label58;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Panel52(lv_event_t * e);
lv_obj_t * ui_Panel52;
lv_obj_t * ui_Label59;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[2] = {&ui_img_0_png, &ui_img_1_png};
const lv_img_dsc_t * ui_imgset_signal[5] = {&ui_img_signal0_png, &ui_img_signal1_png, &ui_img_signal2_png, &ui_img_signal3_png, &ui_img_signal4_png};
const lv_img_dsc_t * ui_imgset_usb[1] = {&ui_img_usb1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_Screen2_screen_init);
        lv_obj_scroll_to_y(ui_Screen2, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
        lv_obj_scroll_to_y(ui_Screen3, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen4_screen_init);
        lv_obj_scroll_to_y(ui_Screen4, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
        lv_obj_scroll_to_y(ui_Screen5, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen6_screen_init);
        lv_obj_scroll_to_y(ui_Screen6, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen7_screen_init);
        lv_obj_scroll_to_y(ui_Screen7, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen8_screen_init);
        lv_obj_scroll_to_y(ui_Screen8, 0, LV_ANIM_OFF);
    }
}
void ui_event_Panel12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_brightness(e);
    }
}
void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_scr_time(e);
    }
}
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_led_signal(e);
    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_battery_warning(e);
    }
}
void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_bat_warn_value(e);
    }
}
void ui_event_Panel19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel24, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Dropdown12, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel25, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel24, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel25, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Dropdown12, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel54, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Panel23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Label24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel24, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        unpair(e);
        _ui_flag_modify(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel25, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Dropdown12, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel54, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Label25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel24, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Dropdown12, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel25, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Panel54, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Panel25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        pairing(e);
    }
}
void ui_event_Dropdown12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_channel(e);
    }
}
void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_double_touch(e);
    }
}
void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_double_hit(e);
    }
}
void ui_event_Panel30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Panel32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        imu_calibration(e);
    }
}
void ui_event_Panel33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        compass_calibration(e);
    }
}
void ui_event_Panel34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_m_x(e);
    }
}
void ui_event_Dropdown4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_m_y(e);
    }
}
void ui_event_Dropdown5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_m_z(e);
    }
}
void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        mouse_sens_m(e);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        mouse_sens_p(e);
    }
}
void ui_event_Panel41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Dropdown6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_yaw_channel(e);
    }
}
void ui_event_Dropdown7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_pitch_channel(e);
    }
}
void ui_event_Dropdown8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_roll_channel(e);
    }
}
void ui_event_Dropdown9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_yaw_max(e);
    }
}
void ui_event_Dropdown10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_pitch_max(e);
    }
}
void ui_event_Dropdown11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        set_roll_max(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_yaw_offset_m(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_yaw_offset_p(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_pitch_offset_m(e);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_pitch_offset_p(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_roll_offset_m(e);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        set_roll_offset_p(e);
    }
}
void ui_event_Panel52(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen2_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui_Screen6_screen_init();
    ui_Screen7_screen_init();
    ui_Screen8_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
