// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#ifndef _HEAD_TRACKER_UI_H
#define _HEAD_TRACKER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_volt1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_usb;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_joystick;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_volt3;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_battery2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_signal;
extern lv_obj_t * ui_rssi;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label5;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label6;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label7;
void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label8;
void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label9;
void ui_event_Panel11(lv_event_t * e);
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label10;
void ui_event_Panel12(lv_event_t * e);
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label11;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label13;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label14;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label15;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label16;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label17;
void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
void ui_event_Panel19(lv_event_t * e);
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label18;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label19;
void ui_event_Panel21(lv_event_t * e);
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
void ui_event_Panel23(lv_event_t * e);
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel24;
void ui_event_Label24(lv_event_t * e);
extern lv_obj_t * ui_Label24;
void ui_event_Label25(lv_event_t * e);
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
void ui_event_Panel25(lv_event_t * e);
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel54;
extern lv_obj_t * ui_Label61;
void ui_event_Dropdown12(lv_event_t * e);
extern lv_obj_t * ui_Dropdown12;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Label30;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label31;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
void ui_event_Panel30(lv_event_t * e);
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Label32;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Label33;
void ui_event_Panel32(lv_event_t * e);
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label34;
void ui_event_Panel33(lv_event_t * e);
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Label35;
void ui_event_Panel34(lv_event_t * e);
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Label40;
void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Label41;
void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Label42;
void ui_event_Dropdown5(lv_event_t * e);
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Label43;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label44;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Panel41(lv_event_t * e);
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_Label45;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel42;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Panel43;
extern lv_obj_t * ui_Label47;
void ui_event_Dropdown6(lv_event_t * e);
extern lv_obj_t * ui_Dropdown6;
extern lv_obj_t * ui_Panel44;
extern lv_obj_t * ui_Label48;
void ui_event_Dropdown7(lv_event_t * e);
extern lv_obj_t * ui_Dropdown7;
extern lv_obj_t * ui_Panel45;
extern lv_obj_t * ui_Label49;
void ui_event_Dropdown8(lv_event_t * e);
extern lv_obj_t * ui_Dropdown8;
extern lv_obj_t * ui_Panel46;
extern lv_obj_t * ui_Label50;
void ui_event_Dropdown9(lv_event_t * e);
extern lv_obj_t * ui_Dropdown9;
extern lv_obj_t * ui_Panel47;
extern lv_obj_t * ui_Label51;
void ui_event_Dropdown10(lv_event_t * e);
extern lv_obj_t * ui_Dropdown10;
extern lv_obj_t * ui_Panel48;
extern lv_obj_t * ui_Label52;
void ui_event_Dropdown11(lv_event_t * e);
extern lv_obj_t * ui_Dropdown11;
extern lv_obj_t * ui_Panel49;
extern lv_obj_t * ui_Label53;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label54;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Panel50;
extern lv_obj_t * ui_Label55;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label56;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Panel51;
extern lv_obj_t * ui_Label57;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label58;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Panel52(lv_event_t * e);
extern lv_obj_t * ui_Panel52;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_barrety_png);    // assets/barrety.png
LV_IMG_DECLARE(ui_img_usb1_png);    // assets/usb1.png
LV_IMG_DECLARE(ui_img_signal4_png);    // assets/signal4.png
LV_IMG_DECLARE(ui_img_0_png);    // assets/0.png
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_signal0_png);    // assets/signal0.png
LV_IMG_DECLARE(ui_img_signal1_png);    // assets/signal1.png
LV_IMG_DECLARE(ui_img_signal2_png);    // assets/signal2.png
LV_IMG_DECLARE(ui_img_signal3_png);    // assets/signal3.png



LV_FONT_DECLARE(ui_font_fangsong);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
