// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void set_brightness(lv_event_t * e);
void set_scr_time(lv_event_t * e);
void set_led_signal(lv_event_t * e);
void set_battery_warning(lv_event_t * e);
void set_bat_warn_value(lv_event_t * e);
void unpair(lv_event_t * e);
void pairing(lv_event_t * e);
void set_channel(lv_event_t * e);
void set_double_touch(lv_event_t * e);
void set_double_hit(lv_event_t * e);
void imu_calibration(lv_event_t * e);
void compass_calibration(lv_event_t * e);
void set_m_x(lv_event_t * e);
void set_m_y(lv_event_t * e);
void set_m_z(lv_event_t * e);
void mouse_sens_m(lv_event_t * e);
void mouse_sens_p(lv_event_t * e);
void set_yaw_channel(lv_event_t * e);
void set_pitch_channel(lv_event_t * e);
void set_roll_channel(lv_event_t * e);
void set_yaw_max(lv_event_t * e);
void set_pitch_max(lv_event_t * e);
void set_roll_max(lv_event_t * e);
void set_yaw_offset_m(lv_event_t * e);
void set_yaw_offset_p(lv_event_t * e);
void set_pitch_offset_m(lv_event_t * e);
void set_pitch_offset_p(lv_event_t * e);
void set_roll_offset_m(lv_event_t * e);
void set_roll_offset_p(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
