// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#include "../ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(ui_Screen7, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_Screen7, 0, LV_PART_SCROLLBAR | LV_STATE_SCROLLED);

    ui_Panel36 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel36, 80);
    lv_obj_set_height(ui_Panel36, 14);
    lv_obj_set_x(ui_Panel36, 0);
    lv_obj_set_y(ui_Panel36, -73);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel36, lv_color_hex(0x868686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel36, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Panel36);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "OTG设置");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel37 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel37, 80);
    lv_obj_set_height(ui_Panel37, 53);
    lv_obj_set_x(ui_Panel37, 0);
    lv_obj_set_y(ui_Panel37, -37);
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel37, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel37, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel37, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label40 = lv_label_create(ui_Panel37);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, 0);
    lv_obj_set_y(ui_Label40, -16);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "鼠标X轴");
    lv_obj_set_style_text_color(ui_Label40, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label40, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_Panel37);
    lv_dropdown_set_options(ui_Dropdown3, "Yaw\n-Yaw\nPitch\n-Pitch\nRoll\n-Roll");
    lv_obj_set_width(ui_Dropdown3, 70);
    lv_obj_set_height(ui_Dropdown3, 27);
    lv_obj_set_x(ui_Dropdown3, 0);
    lv_obj_set_y(ui_Dropdown3, 8);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Dropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown3, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown3), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x4D4D4D),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x898989),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_Dropdown3), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel38 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel38, 80);
    lv_obj_set_height(ui_Panel38, 53);
    lv_obj_set_x(ui_Panel38, 0);
    lv_obj_set_y(ui_Panel38, 19);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel38, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel38, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel38, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label41 = lv_label_create(ui_Panel38);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, 0);
    lv_obj_set_y(ui_Label41, -16);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "鼠标Y轴");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown4 = lv_dropdown_create(ui_Panel38);
    lv_dropdown_set_options(ui_Dropdown4, "Yaw\n-Yaw\nPitch\n-Pitch\nRoll\n-Roll");
    lv_obj_set_width(ui_Dropdown4, 70);
    lv_obj_set_height(ui_Dropdown4, 27);
    lv_obj_set_x(ui_Dropdown4, 0);
    lv_obj_set_y(ui_Dropdown4, 8);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Dropdown4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown4, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown4), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0x4D4D4D),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0x898989),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_Dropdown4), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel39 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel39, 80);
    lv_obj_set_height(ui_Panel39, 53);
    lv_obj_set_x(ui_Panel39, 0);
    lv_obj_set_y(ui_Panel39, 75);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel39, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel39, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel39, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label42 = lv_label_create(ui_Panel39);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, 0);
    lv_obj_set_y(ui_Label42, -16);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "归零模拟按键");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label42, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown5 = lv_dropdown_create(ui_Panel39);
    lv_dropdown_set_options(ui_Dropdown5,
                            "A\nB\nC\nD\nE\nF\nG\nH\nI\nJ\nK\nL\nM\nN\nO\nP\nQ\nR\nS\nT\nU\nV\nW\nX\nY\nZ\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\nL_CTRL\nL_SHIFT\nL_ALT\nR_CTRL\nR_SHIFT\nR_ALT\nUP\nDOWN\nLEFT\nRIGHT\nBACKSPACE\nTAB\nRETURN\nESC\nINSERT\nDELETE\nPAGE_UP\nPAGE_DOWN\nHOME\nEND\nCAPS_LOCK\nF1\nF2\nF3\nF4\nF5\nF6\nF7\nF8\nF9\nF10\nF11\nF12");
    lv_obj_set_width(ui_Dropdown5, 70);
    lv_obj_set_height(ui_Dropdown5, 27);
    lv_obj_set_x(ui_Dropdown5, 0);
    lv_obj_set_y(ui_Dropdown5, 8);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Dropdown5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown5, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_EDITED);
    lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_SCROLLED);
    lv_obj_set_style_bg_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_SCROLLED);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_Dropdown5), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown5), &lv_font_montserrat_8,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0x4D4D4D),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0x898989),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_Dropdown5), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(lv_dropdown_get_list(ui_Dropdown5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(lv_dropdown_get_list(ui_Dropdown5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(lv_dropdown_get_list(ui_Dropdown5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(lv_dropdown_get_list(ui_Dropdown5), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel40 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel40, 80);
    lv_obj_set_height(ui_Panel40, 53);
    lv_obj_set_x(ui_Panel40, 0);
    lv_obj_set_y(ui_Panel40, 131);
    lv_obj_set_align(ui_Panel40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel40, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel40, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel40, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel40, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel40, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel40, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label43 = lv_label_create(ui_Panel40);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 0);
    lv_obj_set_y(ui_Label43, -13);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "灵敏度");
    lv_obj_clear_flag(ui_Label43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_Panel40);
    lv_obj_set_width(ui_Button9, 20);
    lv_obj_set_height(ui_Button9, 20);
    lv_obj_set_x(ui_Button9, -25);
    lv_obj_set_y(ui_Button9, 8);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button9, &ui_img_0_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_Panel40);
    lv_obj_set_width(ui_Label44, 24);
    lv_obj_set_height(ui_Label44, 14);
    lv_obj_set_x(ui_Label44, 0);
    lv_obj_set_y(ui_Label44, 8);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "0");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label44, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label44, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label44, lv_color_hex(0xC5C5C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label44, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Panel40);
    lv_obj_set_width(ui_Button7, 20);
    lv_obj_set_height(ui_Button7, 20);
    lv_obj_set_x(ui_Button7, 25);
    lv_obj_set_y(ui_Button7, 8);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Button7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button7, &ui_img_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel41 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel41, 80);
    lv_obj_set_height(ui_Panel41, 20);
    lv_obj_set_x(ui_Panel41, 0);
    lv_obj_set_y(ui_Panel41, 171);
    lv_obj_set_align(ui_Panel41, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel41, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel41, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel41, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label45 = lv_label_create(ui_Panel41);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "返回");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label45, &ui_font_fangsong, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown4, ui_event_Dropdown4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown5, ui_event_Dropdown5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel41, ui_event_Panel41, LV_EVENT_ALL, NULL);

}
