// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#ifndef _UI_COMP_PANEL1_H
#define _UI_COMP_PANEL1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel1
#define UI_COMP_PANEL1_PANEL1 0
#define UI_COMP_PANEL1_VOLT1 1
#define UI_COMP_PANEL1_VOLT1_BAR2 2
#define UI_COMP_PANEL1_BATTERY 3
#define UI_COMP_PANEL1_USB 4
#define _UI_COMP_PANEL1_NUM 5
lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
