// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Head_Tracker

#include "../ui.h"


// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 80);
    lv_obj_set_height(cui_Panel1, 14);
    lv_obj_set_x(cui_Panel1, 0);
    lv_obj_set_y(cui_Panel1, -73);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel1, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_volt1;
    cui_volt1 = lv_img_create(cui_Panel1);
    lv_img_set_src(cui_volt1, &ui_img_barrety_png);
    lv_obj_set_width(cui_volt1, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(cui_volt1, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(cui_volt1, 30);
    lv_obj_set_y(cui_volt1, 0);
    lv_obj_set_align(cui_volt1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_volt1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_volt1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Bar2;
    cui_Bar2 = lv_bar_create(cui_volt1);
    lv_bar_set_value(cui_Bar2, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Bar2, 13);
    lv_obj_set_height(cui_Bar2, 7);
    lv_obj_set_align(cui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(cui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Bar2, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(cui_Bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Bar2, lv_color_hex(0x363936), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t * cui_battery;
    cui_battery = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_battery, 12);
    lv_obj_set_y(cui_battery, 0);
    lv_obj_set_align(cui_battery, LV_ALIGN_CENTER);
    lv_label_set_text(cui_battery, "100");
    lv_obj_set_style_text_color(cui_battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_battery, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_usb;
    cui_usb = lv_img_create(cui_Panel1);
    lv_img_set_src(cui_usb, &ui_img_usb1_png);
    lv_obj_set_width(cui_usb, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(cui_usb, LV_SIZE_CONTENT);    /// 7
    lv_obj_set_x(cui_usb, -27);
    lv_obj_set_y(cui_usb, -1);
    lv_obj_set_align(cui_usb, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_usb, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_usb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    children[UI_COMP_PANEL1_VOLT1] = cui_volt1;
    children[UI_COMP_PANEL1_VOLT1_BAR2] = cui_Bar2;
    children[UI_COMP_PANEL1_BATTERY] = cui_battery;
    children[UI_COMP_PANEL1_USB] = cui_usb;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

